apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-varnish-teste
  namespace: teste-varnish
spec:
  selector:
    matchLabels:
      app: varnish-teste
  template:
    metadata:
      labels:
        app: varnish-teste
    spec:
      volumes: #Declara o volume, nesse caso será utilizado um ConfigMap
        - name: varnish-config
          secret:
            secretName: varnish-config-secret #NOME DO CONFIGMAP QUE SERÁ UTILIZADO
      containers:
      - name: varnish-teste
        image: varnish:7.2.1
        #Define privilegio de exeecução do POD, elimina o erro de permissão da porta 80 no varnish
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        resources:
          requests:
            memory: "128Mi"
            cpu: "0.5m"
          limits:
            memory: "256Mi"
            cpu: "1m"
        ports:
        - containerPort: 80
        volumeMounts: #Indica o volume que será usado
          - name: varnish-config
            mountPath: "/etc/varnish/" #mapeia onde será montado o volume dentro do POD
