apiVersion: v1
kind: Secret
metadata:
  name: varnish-config-secret
type: Opaque
data:
  #Use o comando "base64 nome_do_arquivo.vcl" para configurar o arquivo como base64 no secret
  default.vcl: |
    IyBzcGVjaWZ5IHRoZSBWQ0wgc3ludGF4IHZlcnNpb24gdG8gdXNlDQp2Y2wgNC4xOw0KDQojIGlt
    cG9ydCB2bW9kX2R5bmFtaWMgZm9yIGJldHRlciBiYWNrZW5kIG5hbWUgcmVzb2x1dGlvbg0KaW1w
    b3J0IGR5bmFtaWM7DQoNCiMgd2Ugd29uJ3QgdXNlIGFueSBzdGF0aWMgYmFja2VuZCwgYnV0IFZh
    cm5pc2ggc3RpbGwgbmVlZCBhIGRlZmF1bHQgb25lDQpiYWNrZW5kIGRlZmF1bHQgbm9uZTsNCg0K
    IyBzZXQgdXAgYSBkeW5hbWljIGRpcmVjdG9yDQojIGZvciBtb3JlIGluZm8sIHNlZSBodHRwczov
    L2dpdGh1Yi5jb20vbmlnb3JvbGwvbGlidm1vZC1keW5hbWljL2Jsb2IvbWFzdGVyL3NyYy92bW9k
    X2R5bmFtaWMudmNjDQpzdWIgdmNsX2luaXQgew0KICAgICAgICBuZXcgZCA9IGR5bmFtaWMuZGly
    ZWN0b3IocG9ydCA9ICI4MCIpOw0KfQ0KDQpzdWIgdmNsX3JlY3Ygew0KCSMgZm9yY2UgdGhlIGhv
    c3QgaGVhZGVyIHRvIG1hdGNoIHRoZSBiYWNrZW5kIChub3QgYWxsIGJhY2tlbmRzIG5lZWQgaXQs
    DQoJIyBidXQgZXhhbXBsZS5jb20gZG9lcykNCglzZXQgcmVxLmh0dHAuaG9zdCA9ICJleGFtcGxl
    LmNvbSI7DQoJIyBzZXQgdGhlIGJhY2tlbmQNCglzZXQgcmVxLmJhY2tlbmRfaGludCA9IGQuYmFj
    a2VuZCgiZXhhbXBsZS5jb20iKTsNCn0=