apiVersion: v1
kind: Secret
metadata:
  name: secret-varnish-teste
  namespace: varnish-teste
type: Opaque
data:
  #Use o comando "base64 nome_do_arquivo.vcl" para configurar o arquivo como base64 no secret
  default.vcl: |
    dmNsIDQuMTsNCmltcG9ydCBzdGQ7DQoNCmJhY2tlbmQgdGVzdGUgew0KCS5ob3N0ID0gIjEwLjEz
    Mi4yMDguMjIyIjsNCiAgICAucG9ydCA9ICI5MDAwIjsNCn0NCg0Kc3ViIHZjbF9yZWN2IHsNCg0K
    CWlmIChyZXEuaHR0cC5ob3N0ID09ICJ0ZXN0ZXZhcm5pc2gudWNvbW1lcmNlLmNvbS5iciIpIHsN
    CgkJc2V0IHJlcS5iYWNrZW5kX2hpbnQgPSB0ZXN0ZTsNCgl9DQoNCg0KCWlmIChyZXEucmVzdGFy
    dHMgPT0gMCkgew0KICAgICAgICAgIGlmIChyZXEuaHR0cC5YLUZvcndhcmRlZC1Gb3IpIHsNCgkJ
    c2V0IHJlcS5odHRwLlgtRm9yd2FyZGVkLUZvciA9IHJlcS5odHRwLngtcmVhbC1pcDsNCiAgICAg
    ICAgICB9IGVsc2Ugew0KCQlzZXQgcmVxLmh0dHAuWC1Gb3J3YXJkZWQtRm9yID0gcmVxLmh0dHAu
    eC1yZWFsLWlwOw0KCSAgfQ0KCX0NCg0KCWlmIChyZXEuaHR0cC5BdXRob3JpemF0aW9uIHx8IHJl
    cS5tZXRob2QgPT0gIlBPU1QiKSB7DQoJCXJldHVybiAocGFzcyk7DQoJfQ0KDQoJaWYgKHJlcS51
    cmwgfiAiL2ZlZWQiKSB7DQoJCXJldHVybiAocGFzcyk7DQoJfQ0KDQoJaWYgKHJlcS5odHRwLlVz
    ZXItQWdlbnQgfiAiKE1vYmlsZXxBbmRyb2lkfGlQaG9uZXxpUGFkfFN5bWJpYW5PU3xeQmxhY2tC
    ZXJyeSkiKSB7DQoJCSNyZXR1cm4gKHBhc3MpOw0KCQlzZXQgcmVxLmh0dHAuWC1EZXZpY2UgPSAi
    c21hcnQiOw0KCX0NCg0KCSNFWENMVVPDg08gREUgVEVSTU9TIE5BIFVSTCBETyBTSVRFDQoJaWYg
    KHJlcS51cmwgfiAiLyh1LWFkbWlufHBvc3RcLnBocHxlZGl0XC5waHB8d3AtYWRtaW58d3AtbG9n
    aW58Y2FycmluaG98Y2FydHxvcmNhbWVudG98Y2hlY2tvdXR8bWluaGEtY29udGF8bXktYWNjb3Vu
    dHxcP2FkZC10by1jYXJ0PXxhZGQtdG8tY2FydHxpbnRlcmlvcnxzZWFyY2h8d3AtY29udGVudHx3
    cC1pbmNsdWRlc3x3cC1qc29ufHdjLWFwaS8qfGFkZG9uc3xsb2dvdXR8bG9zdC1wYXNzd29yZCki
    KSB7DQoJICAgIHJldHVybiAocGFzcyk7DQoJfQ0KDQoJICMgRXhjbHVkZSB3cC1jcm9uIG9yIHdo
    ZW4gdGhlIGZyb250IGVuZCBpcyBiZWluZw0KCSAjIHByZXZpZXdlZCBmcm9tIHRoZSBhZG1pbmlz
    dHJhdG9yL2RldmVsb3Blcg0KCSBpZiAocmVxLnVybCB+ICIvd3AtY3Jvbi5waHAiIHx8IHJlcS51
    cmwgfiAicHJldmlldz10cnVlIikgew0KCSAgICAgcmV0dXJuIChwYXNzKTsNCgkgfQ0KDQoJIyBF
    eGNsdWRlIGV2ZXJ5dGhpbmcgdGhhdCBpcyBuZWl0aGVyIEdFVCBub3IgSEVBRA0KCWlmIChyZXEu
    bWV0aG9kICE9ICJHRVQiICYmIHJlcS5tZXRob2QgIT0gIkhFQUQiKSB7DQoJICAgICByZXR1cm4g
    KHBhc3MpOw0KCX0NCg0KCSMgRXhjbHVkZSBjYWNoaW5nIEFqYXggcmVxdWVzdHMNCglpZiAocmVx
    Lmh0dHAuWC1SZXF1ZXN0ZWQtV2l0aCA9PSAiWE1MSHR0cFJlcXVlc3QiKSB7DQoJICAgICByZXR1
    cm4ocGFzcyk7DQoJfQ0KDQoJaWYgKHJlcS51cmwgfiAiYWRkZWRfaXRlbT0iICkgew0KCQlyZXR1
    cm4gKHBhc3MpOw0KCX0NCg0KCWlmIChyZXEudXJsIH4gIm9yY2FtZW50by9hZGRlZF9pdGVtIiAp
    IHsNCgkJcmV0dXJuIChwYXNzKTsNCgl9DQoNCglpZiAocmVxLnVybCB+ICJ1cGRhdGVkX2l0ZW0i
    ICkgew0KCQlyZXR1cm4gKHBhc3MpOw0KCX0NCg0KCSMgUGFzcyB0aHJvdWdoIHRoZSBXb29Db21t
    ZXJjZSBBUEkNCglpZiAocmVxLnVybCB+ICJcP3djLWFwaT0iICkgew0KCQlyZXR1cm4gKHBhc3Mp
    Ow0KCX0NCg0KCWlmIChyZXEudXJsIH4gIlw/d2MtYWpheD0iICkgew0KCQlyZXR1cm4gKHBhc3Mp
    Ow0KCX0NCg0KCWlmIChyZXEuaHR0cC5jb29raWUgfiAid29vY29tbWVyY2VfY2FydF9oYXNoIiB8
    fCByZXEuaHR0cC5jb29raWUgfiAid29vY29tbWVyY2VfaXRlbXNfaW5fY2FydCIgfHwgIHJlcS5o
    dHRwLmNvb2tpZSB+ICJ3b3JkcHJlc3NfbG9nZ2VkX2luIiB8fCAgcmVxLmh0dHAuY29va2llIH4g
    InJlc2V0cGFzcyIgKXsNCgkJcmV0dXJuIChwYXNzKTsNCgl9DQoNCglpZiAocmVxLnVybCB+ICJe
    L3RleHQucGhwJCIpIHsNCgkJcmV0dXJuIChwYXNzKTsNCgl9DQoNCglpZiAocmVxLnVybCB+ICJe
    L3htbHJwYy5waHAkIikgew0KCQlyZXR1cm4gKHBhc3MpOw0KCX0NCg0KCWlmIChyZXEudXJsIH4g
    Il4vaW5zdGFsbGVyLnBocCQiKSB7DQoJCXJldHVybiAocGFzcyk7DQoJfQ0KDQoJdW5zZXQgcmVx
    Lmh0dHAuY29va2llOw0KDQp9DQoNCnN1YiB2Y2xfaGFzaCB7DQoJaWYgKHJlcS5odHRwLlgtRGV2
    aWNlIH4gInNtYXJ0IiApIHsNCgkJaGFzaF9kYXRhKHJlcS5odHRwLlgtRGV2aWNlKTsNCgl9DQp9
    DQoNCnN1YiB2Y2xfYmFja2VuZF9yZXNwb25zZSB7DQoNCgkjRVhDTFVTw4NPIERFIFRFUk1PUyBO
    QSBVUkwgRE8gU0lURQ0KCWlmICgoYmVyZXEudXJsICF+ICIvKGFkZC10by1jYXJ0fFw/YWRkLXRv
    LWNhcnQ9fHBvc3RcLnBocHxlZGl0XC5waHB8dS1hZG1pbnx3cC1hZG1pbnx3cC1sb2dpbnxjYXJy
    aW5ob3xvcmNhbWVudG98Y2hlY2tvdXR8bWluaGEtY29udGF8bXktYWNjb3VudHxpbnRlcmlvcnxz
    ZWFyY2h8d3AtY29udGVudHx3cC1pbmNsdWRlc3x3cC1qc29ufHdjLWFwaS8qfGFkZG9uc3xsb2dv
    dXR8bG9zdC1wYXNzd29yZCkiKSAmJiAoYmVyZXEuaHR0cC5jb29raWUgIX4gIndvb2NvbW1lcmNl
    X2NhcnRfaGFzaCIgfHwgYmVyZXEuaHR0cC5jb29raWUgIX4gIndvb2NvbW1lcmNlX2l0ZW1zX2lu
    X2NhcnQiIHx8ICBiZXJlcS5odHRwLmNvb2tpZSAhfiAid29yZHByZXNzX2xvZ2dlZF9pbiIgfHwg
    IGJlcmVxLmh0dHAuY29va2llICF+ICJyZXNldHBhc3MiKSAmJiAoYmVyZXNwLnN0YXR1cyAhPSAz
    MDIpKQ0KCXsNCgkJdW5zZXQgYmVyZXNwLmh0dHAuc2V0LWNvb2tpZTsNCgkJc2V0IGJlcmVzcC50
    dGwgPSAxaDsNCgkJc2V0IGJlcmVzcC5ncmFjZSA9IDJoOw0KCX0NCg0KCWlmIChiZXJlcS51cmwg
    fiAiXi90ZXh0LnBocCQiKSB7DQoJCXVuc2V0IGJlcmVzcC5odHRwLnNldC1jb29raWU7DQoJfQ0K
    DQoJaWYgKGJlcmVxLnVybCB+ICJeL3htbHJwYy5waHAkIikgew0KCQl1bnNldCBiZXJlc3AuaHR0
    cC5zZXQtY29va2llOw0KCX0NCn0NCg0Kc3ViIHZjbF9kZWxpdmVyIHsNCgl1bnNldCByZXNwLmh0
    dHAuTGluazsNCgl1bnNldCByZXNwLmh0dHAuVmlhOw0KCXVuc2V0IHJlc3AuaHR0cC5YLVZhcm5p
    c2g7DQoJdW5zZXQgcmVzcC5odHRwLkFnZTsNCg0KCWlmIChvYmouaGl0cyA+IDApIHsNCgkgICAg
    ICAgIHNldCByZXNwLmh0dHAuWC1DYWNoZSA9ICJISVQiOw0KCX1lbHNlew0KCSAgICAgICAgc2V0
    IHJlc3AuaHR0cC5YLUNhY2hlID0gIk1JU1MiOw0KCX0NCn0NCg==