apiVersion: v1
kind: Secret
metadata:
  name: varnish-config-secret
  namespace: teste-varnish
type: Opaque
data:
  #Use o comando "base64 nome_do_arquivo.vcl" para configurar o arquivo como base64 no secret
  default.vcl: |
    IyBzcGVjaWZ5IHRoZSBWQ0wgc3ludGF4IHZlcnNpb24gdG8gdXNlDQp2Y2wgNC4xOw0KDQojIGlt
    cG9ydCB2bW9kX2R5bmFtaWMgZm9yIGJldHRlciBiYWNrZW5kIG5hbWUgcmVzb2x1dGlvbg0KaW1w
    b3J0IHN0ZDsNCg0KIyB3ZSB3b24ndCB1c2UgYW55IHN0YXRpYyBiYWNrZW5kLCBidXQgVmFybmlz
    aCBzdGlsbCBuZWVkIGEgZGVmYXVsdCBvbmUNCmJhY2tlbmQgdGVzdGUgew0KCS5ob3N0ID0gIjEw
    LjEzMi4yMDguMjIyIjsNCiAgICAucG9ydCA9ICI4MDgyIjsNCn0NCg0Kc3ViIHZjbF9yZWN2IHsN
    CglpZiAocmVxLmh0dHAuaG9zdCA9PSAid3d3LnRlc3RlLmNvbS5iciIpIHsNCgkJc2V0IHJlcS5i
    YWNrZW5kX2hpbnQgPSB0ZXN0ZTsNCgl9DQp9